export type MCQ = {
  id: string;
  type: 'mcq';
  prompt: string;
  options: string[];
  correctIndex: number;
  explanation: string;
  hint?: string;
  detailedExplanation?: string;
  codeExample?: string;
  analogy?: string;
  difficulty?: 'easy' | 'medium' | 'hard';
};

export type Exercise = MCQ;

export function getExercisesFor(slug: string): Exercise[] {
  if (slug === '01-variaveis-e-tipos') {
    const list: MCQ[] = [
      {
        id: 'q1',
        type: 'mcq',
        prompt: 'Qual é a melhor escolha para declarar uma variável cujo valor NÃO muda?',
        options: ['var', 'let', 'const', 'number'],
        correctIndex: 2,
        explanation: 'Use const para valores que não serão reatribuídos; let para valores mutáveis; evite var.',
        hint: 'Pense na palavra-chave que significa "constante".',
        detailedExplanation: 'Em JavaScript moderno (ES6+): var (legada), let (mutável) e const (imutável). Prefira const por padrão e use let quando precisar reatribuir.',
        analogy: '🔐 const é um cofre trancado; let é uma caixa; var é uma caixa velha com problemas.',
        codeExample: '// const não permite reatribuição\nconst PI = 3.14;\n// PI = 3.1415; // ERRO\nlet pontos = 0; pontos++;\nvar antigo = 1; // evite var',
        difficulty: 'easy',
      },
      {
        id: 'q2',
        type: 'mcq',
        prompt: 'Qual o resultado de typeof null?',
        options: ['\'null\'', '\'object\'', '\'undefined\'', '\'boolean\''],
        correctIndex: 1,
        explanation: "Por uma peculiaridade histórica, typeof null retorna 'object'.",
        hint: 'Pegadinha famosa da linguagem.',
        detailedExplanation: "null é um primitivo, mas typeof null retorna 'object' por legado histórico. Para checar null use valor === null.",
        codeExample: 'console.log(typeof null); // "object"\nconsole.log(null === null); // true',
        difficulty: 'easy',
      },
      {
        id: 'q3',
        type: 'mcq',
        prompt: "Qual chamada converte a string '42' em número 42?",
        options: ["String('42')", "Number('42')", "Boolean('42')", "+'42' + '0'"],
        correctIndex: 1,
        explanation: "Number('42') retorna o número 42.",
        hint: 'Use a função com o nome do tipo desejado.',
        detailedExplanation: 'Também funcionam parseInt("42"), parseFloat("42.0") e o operador +"42". Cuidado com strings inválidas: Number("abc") => NaN.',
        codeExample: 'const n = Number("42");\nconsole.log(n, typeof n); // 42 "number"',
        difficulty: 'easy',
      },
      {
        id: 'q4',
        type: 'mcq',
        prompt: 'Qual expressão é verdadeira?',
        options: [
          'null === undefined',
          'null == undefined',
          'Boolean(0) === true',
          "typeof 9007199254740991n === 'number'",
        ],
        correctIndex: 1,
        explanation: 'null == undefined é true (igualdade frouxa). Já === é false.',
        hint: 'Lembre da diferença entre == e ===.',
        detailedExplanation: '== permite coerção de tipos; === compara valor e tipo. Prefira sempre ===.',
        codeExample: 'console.log(null == undefined); // true\nconsole.log(null === undefined); // false',
        difficulty: 'medium',
      },
      {
        id: 'q5',
        type: 'mcq',
        prompt: 'Qual opção descreve corretamente bigint?',
        options: [
          'Um tipo para strings muito grandes',
          'Um número inteiro arbitrariamente grande, escrito com sufixo n',
          'Um alias para number',
          'Um objeto especial do DOM',
        ],
        correctIndex: 1,
        explanation: 'bigint representa inteiros arbitrariamente grandes: ex.: 9007199254740991n.',
        hint: 'A opção com sufixo n.',
        detailedExplanation: 'BigInt não sofre o limite de segurança do Number (2^53 - 1).',
        codeExample: 'const x = 9007199254740993n;\nconsole.log(typeof x); // "bigint"',
        difficulty: 'medium',
      },
      {
        id: 'q6',
        type: 'mcq',
        prompt: 'Qual é a diferença correta entre null e undefined?',
        options: [
          'undefined é ausência intencional e null é variável não inicializada',
          'Ambos significam exatamente a mesma coisa',
          'undefined = variável existe mas sem valor; null = vazio intencional',
          'null é uma string vazia especial',
        ],
        correctIndex: 2,
        explanation: 'undefined aparece quando algo não recebeu valor; null é atribuído de propósito para indicar vazio.',
        hint: 'Um vem “de graça”; o outro você coloca.',
        detailedExplanation: 'let x; // undefined. let y = null; // vazio intencional.',
        codeExample: 'let a; let b = null;\nconsole.log(a === undefined, b === null); // true true',
        difficulty: 'easy',
      },
      {
        id: 'q7',
        type: 'mcq',
        prompt: 'Qual expressão identifica corretamente se um valor é NaN?',
        options: [
          'valor === NaN',
          'Number.isNaN(valor)',
          'typeof valor === "nan"',
          'isFinite(NaN)',
        ],
        correctIndex: 1,
        explanation: 'NaN nunca é igual a ele mesmo; use Number.isNaN(valor).',
        hint: 'Evite comparar com ===.',
        detailedExplanation: 'isNaN() faz coerção; Number.isNaN() é mais precisa.',
        codeExample: 'const x = NaN;\nconsole.log(Number.isNaN(x)); // true',
        difficulty: 'medium',
      },
      {
        id: 'q8',
        type: 'mcq',
        prompt: 'Qual destes valores é FALSY?',
        options: ['"0"', '[]', '" "', '0'],
        correctIndex: 3,
        explanation: '0 é falsy; strings não vazias e array vazio são truthy.',
        hint: 'A lista de falsy é curta.',
        detailedExplanation: 'Falsy: false, 0, -0, 0n, "", null, undefined, NaN.',
        codeExample: 'if (0) { console.log("truthy"); } else { console.log("falsy"); }',
        difficulty: 'easy',
      },
      {
        id: 'q9',
        type: 'mcq',
        prompt: 'Qual é o resultado de typeof [] (array vazio)?',
        options: ['"array"', '"object"', '"list"', '"iterable"'],
        correctIndex: 1,
        explanation: 'Arrays são objetos especiais; typeof [] => "object".',
        hint: 'Para arrays, use Array.isArray.',
        detailedExplanation: 'typeof não distingue arrays de objetos comuns.',
        codeExample: 'console.log(typeof []); // "object"\nconsole.log(Array.isArray([])); // true',
        difficulty: 'easy',
      },
      {
        id: 'q10',
        type: 'mcq',
        prompt: 'Qual afirmação sobre let e const está CORRETA?',
        options: [
          'Objetos criados com const não podem ter propriedades alteradas',
          'Variáveis let têm escopo global sempre',
          'const impede reatribuição; conteúdo interno de objetos/arrays ainda pode mudar',
          'let e var funcionam iguais em escopo',
        ],
        correctIndex: 2,
        explanation: 'const congela a referência, não o conteúdo.',
        hint: 'A “caixa” não troca; o conteúdo pode.',
        detailedExplanation: 'Para congelar conteúdo use Object.freeze.',
        codeExample: 'const u = { pontos: 1 }; u.pontos = 2; // ok',
        difficulty: 'medium',
      },
      {
        id: 'q11',
        type: 'mcq',
        prompt: 'Qual é o resultado de typeof function(){}?',
        options: ['"object"', '"callable"', '"function"', '"method"'],
        correctIndex: 2,
        explanation: 'typeof uma função retorna "function".',
        hint: 'É um caso especial do typeof.',
        detailedExplanation: 'Apesar de funções serem objetos, typeof destaca "function".',
        codeExample: 'console.log(typeof function(){}); // "function"',
        difficulty: 'easy',
      },
      {
        id: 'q12',
        type: 'mcq',
        prompt: 'Qual conversão para boolean é CORRETA?',
        options: [
          'Boolean("") === true',
          'Boolean("false") === false',
          'Boolean("0") === true',
          'Boolean(0) === false',
        ],
        correctIndex: 3,
        explanation: '0 é falsy. Strings não vazias são truthy (inclusive "0" e "false").',
        hint: 'Só string vazia é falsy.',
        detailedExplanation: 'Boolean("") => false; Boolean("algo") => true.',
        codeExample: 'console.log(Boolean(""), Boolean("0")); // false true',
        difficulty: 'easy',
      },
      {
        id: 'q13',
        type: 'mcq',
        prompt: 'Qual opção descreve CORRETAMENTE parseInt vs Number?',
        options: [
          'parseInt mantém decimais, Number descarta',
          'parseInt pode usar base (radix), Number não; Number converte inteiro e decimal',
          'Ambos se comportam iguais',
          'Number sempre retorna inteiro',
        ],
        correctIndex: 1,
        explanation: 'parseInt("10", 2) interpreta como binário; Number trata como número decimal se válido.',
        hint: 'Lembre do parâmetro radix.',
        detailedExplanation: 'parseInt lida com inteiros e base; Number converte ponto flutuante completo.',
        codeExample: 'console.log(parseInt("08", 10)); // 8\nconsole.log(Number("08.5")); // 8.5',
        difficulty: 'medium',
      },
      {
        id: 'q14',
        type: 'mcq',
        prompt: 'Qual é o resultado de typeof 123n?',
        options: ['"number"', '"bigint"', '"numeric"', '"integer"'],
        correctIndex: 1,
        explanation: 'Literals com n são BigInt.',
        hint: 'Olhe o sufixo.',
        detailedExplanation: 'BigInt é um tipo separado de Number.',
        codeExample: 'console.log(typeof 123n); // "bigint"',
        difficulty: 'easy',
      },
      {
        id: 'q15',
        type: 'mcq',
        prompt: 'Qual comparação é TRUE usando == (frouxa)?',
        options: [
          '"5" === 5',
          '0 == false',
          'null === undefined',
          '"" === false',
        ],
        correctIndex: 1,
        explanation: '0 == false é true por coerção; prefira === para evitar esse tipo de armadilha.',
        hint: 'Com == há coerção entre 0 e false.',
        detailedExplanation: 'Com ===, todas as comparações listadas seriam false.',
        codeExample: 'console.log(0 == false); // true\nconsole.log(0 === false); // false',
        difficulty: 'medium',
      },
      {
        id: 'q16',
        type: 'mcq',
        prompt: 'Qual é a melhor forma de verificar se um valor é um array?',
        options: ['typeof valor === "array"', 'valor instanceof Array', 'Array.isArray(valor)', 'typeof valor === "object" && valor.length'],
        correctIndex: 2,
        explanation: 'Array.isArray(valor) é a forma padronizada e confiável.',
        hint: 'Existe um método específico no objeto Array.',
        detailedExplanation: 'typeof [] retorna "object". instanceof pode falhar com iframes diferentes. Array.isArray é consistente.',
        codeExample: 'console.log(Array.isArray([])); // true\nconsole.log(typeof []); // "object"',
        difficulty: 'hard',
      },
      {
        id: 'q17',
        type: 'mcq',
        prompt: 'Qual alternativa identifica corretamente um Symbol?',
        options: ['typeof Symbol() === "symbol"', 'typeof Symbol() === "object"', 'Symbol() instanceof Symbol', 'Number(Symbol()) === 0'],
        correctIndex: 0,
        explanation: 'typeof Symbol() retorna "symbol".',
        hint: 'O typeof tem um valor dedicado para esse tipo.',
        detailedExplanation: 'Symbols são únicos e usados como chaves ocultas. Symbol() instanceof Symbol é false porque Symbol não é construtor tradicional.',
        codeExample: 'const s = Symbol("id");\nconsole.log(typeof s); // "symbol"',
        difficulty: 'hard',
      },
      {
        id: 'q18',
        type: 'mcq',
        prompt: 'Qual expressão diferencia corretamente Object.is(NaN, NaN) de NaN === NaN?',
        options: [
          'NaN === NaN é true e Object.is(NaN, NaN) é false',
          'Ambos são false',
          'NaN === NaN é false e Object.is(NaN, NaN) é true',
          'Ambos são true',
        ],
        correctIndex: 2,
        explanation: 'Object.is trata NaN como igual a NaN; === considera NaN diferente de si mesmo.',
        hint: 'Object.is tem semântica ligeiramente diferente de ===.',
        detailedExplanation: 'Object.is é mais preciso para distinguir -0 de 0 e para comparar NaN corretamente.',
        codeExample: 'console.log(NaN === NaN); // false\nconsole.log(Object.is(NaN, NaN)); // true',
        difficulty: 'hard',
      },
      {
        id: 'q19',
        type: 'mcq',
        prompt: 'O que acontece ao tentar somar 10n + 5 (BigInt + Number)?',
        options: [
          'Retorna 15n',
          'Retorna 15',
          'Lança erro de TypeError',
          'Converte automaticamente para number',
        ],
        correctIndex: 2,
        explanation: 'Não é permitido operar diretamente BigInt com Number sem conversão explícita.',
        hint: 'Misturar tipos numéricos dá erro.',
        detailedExplanation: 'Você precisa converter: 10n + BigInt(5) ou Number(10n) + 5.',
        codeExample: '// 10n + 5 // TypeError\nconsole.log(10n + 5n); // 15n',
        difficulty: 'hard',
      },
      {
        id: 'q20',
        type: 'mcq',
        prompt: 'Qual comparação retorna true envolvendo coerção inesperada?',
        options: [
          '"" == 0',
          '"0" == 0',
          'false == "false"',
          '[] == false',
        ],
        correctIndex: 1,
        explanation: '"0" == 0 é true por coerção de string para número.',
        hint: 'Lembre que == faz conversões agressivas.',
        detailedExplanation: 'Evite == para evitar surpresas como [] == false (true) ou "0" == 0 (true).',
        codeExample: 'console.log("0" == 0); // true\nconsole.log("0" === 0); // false',
        difficulty: 'hard',
      },
    ];
    return list;
  }
  return [];
}
